QQR_category_mapping = {
    "Disease": "疾病",
    "Symptom": "症状(患者感受)",
    "Sign": "体征(医生检测）",
    "Pregnancy-related Activity": "怀孕相关",
    "Neoplasm Status": "肿瘤进展",
    "Non-Neoplasm Disease Stage": "疾病分期",
    "Allergy Intolerance": "过敏耐受",
    "Organ or Tissue Status": "器官组织状态",
    "Life Expectancy": "预期寿命",
    "Oral related": "口腔相关",
    "Pharmaceutical Substance or Drug": "药物",
    "Therapy or Surgery": "治疗或手术",
    "Device": "设备",
    "Nursing": "护理",
    "Diagnostic": "诊断",
    "Laboratory Examinations": "实验室检查",
    "Risk Assessment": "风险评估",
    "Receptor Status": "受体状态",
    "Age": "年龄",
    "Special Patient Characteristic": "特殊病人特征",
    "Literacy": "读写能力",
    "Gender": "性别",
    "Education": "教育情况",
    "Address": "居住情况",
    "Ethnicity": "种族",
    "Consent": "知情同意",
    "Enrollment in other studies": "参与其它试验",
    "Researcher Decision": "研究者决定",
    "Capacity": "能力",
    "Ethical Audit": "伦理审查",
    "Compliance with Protocol": "依存性",
    "Addictive Behavior": "成瘾行为",
    "Bedtime": "睡眠",
    "Exercise": "锻炼",
    "Diet": "饮食",
    "Alcohol Consumer": "酒精使用",
    "Sexual related": "性取向",
    "Smoking Status": "吸烟状况",
    "Blood Donation": "献血",
    "Encounter": "病例来源",
    "Disabilities": "残疾群体",
    "Healthy": "健康群体",
    "Data Accessible": "数据可及性",
    "Multiple": "含有多类别的语句"
}
QIC_categories = {
    "diagnosis": "病情诊断",
    "cause": "病因分析",
    "method": "治疗方案",
    "advice": "就医建议",
    "metric_explain": "指标解读",
    "Ndisease_express": "疾病描述",
    "result": "后果表述",
    "attention": "注意事项",
    "effect": "功效作用",
    "price": "医疗费用",
    "other": "其他",
}
QQR_choice=["完全一致", "后者是前者的语义子集", "后者是前者的语义父集", "语义无直接关联"]
CMeEE_category_mapping = {
    "dis":"疾病",
    "ite":"医学检验项目",
    "dep":"医院科室",
    "bod":"身体部位",
    "mic":"微生物类",
    "sym":"临床表现",
    "dru":"药物",
    "equ":"医疗设备",
    "pro":"医疗程序"
}